steps:
    # Build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple-flask-image:latest', '.']
    # push container image to registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/simple-flask-image:latest']
    # Deploy container image to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['run', 'deploy', 'simple-flask', '--image', 'gcr.io/$PROJECT_ID/simple-flask-image:latest', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
# options:
#   machineType: 'N1_HIGHCPU_32'